PrintComment: ThisGoesHere is deleting unwanted files, specialised for JothorHeim
DeleteFolder:
- plugins\WackyMole-RareMagicPortal
- config\WackyMole.RareMagicPortal.cfg
- plugins\OdinPlus-OdinsKingdom
- config\odinplus.plugins.odinskingdom.cfg
